### ISSUE TITLE
.fasta size requirement? 

### ISSUE THREAD

**Issue by yanboANU** [felipelouza/egap#4]
Hello, when input .fasta file size smaller than 2G (I tested on 2.5M, 25M, 242M, and 1.2G), eGap works well. Example of run 1.2G test.fasta:

/egap/eGap -m 4096 test.fasta
Sending logging messages to file: test.fasta.eGap.log
==== gSACAK
 Command: egap/tools/gsacak -b -m 4096  test.fasta 0
Elapsed time: 810.9151
==== gap (internal memory)
 Command: egap/gap2 -g256 -vaT test.fasta
Elapsed time: 0.0030
==== Done
Total construction time: 810.9186   usec/byte: 0.6478 (outsize: 1251720450)

While when test.fasta is 2.2G, I failed.  

egap/eGap -m 4096 test2.fasta
Sending logging messages to file: test2.fasta.eGap.log
==== gSACAK
 Command: egap/tools/gsacak -b -m 4096  test2.fasta 0
Error executing command line:
	egap/tools/gsacak -b -m 4096  test2.fasta 0
Check log file: test2.fasta.eGap.log

I try to increase -m, but still failed.
egap/eGap -m 8096 test2.fasta
Sending logging messages to file: test2.fasta.eGap.log
==== gSACAK
 Command: egap/tools/gsacak -b -m 8096  test2.fasta 0
Error executing command line:
	egap/tools/gsacak -b -m 8096  test2.fasta 0
Check log file: test2.fasta.eGap.log

The content in test2.fasta.eGap.log:
>>> Begin computation
Python command line: egap/eGap -m 8096 test2.fasta 
--- Phase 1 ---

And I continue to run "egap/tools/gsacak -b -m 8096  test2.fasta 0",  I meet a Segmentation fault.
egap/tools/gsacak -b -m 8096  test2.fasta 0
##
RAM = 7.91 GB
max(chunk) = 1697854259 symbols
K = 1
N = 18446744071741255078
CHUNKS = 1
sizeof(int_t) = 4 bytes
##
Segmentation fault

Could do tell me what have I done wrong? Thanks.

**Comment by yanboANU** [comment]
I first thought tests of input size smaller than 2G are all correct. But when I look the .bwt file, there are two different types of .bwt. 
My input is fasta file and reads only contain "A",  "T",  "C",  "G".  If input size is 2.5M, the .bwt file is correct, it's a string of "A",  "T",  "C",  "G". But if input size is 1.5G, the .bwt file seems wrong, it's a string of "A",  "1",  "2".
 Could do tell me what have I done wrong? Thanks.

Example of 1.5G:
Sending logging messages to file: single_chr22_40x_data.fasta.eGap.log
==== gSACAK
 Command: egap/tools/gsacak -b -m 4096  single_chr22_40x_data.fasta 0
Elapsed time: 1394.6841
==== gap (semi-external memory)
 Command: egap/gap2 -A8 -g8 -vaE single_chr22_40x_data.fasta
Elapsed time: 0.0031
==== Done
Total construction time: 1394.6874   usec/byte: 0.8997 (outsize: 1550100296)


cat single_chr22_40x_data.fasta.eGap.log 
>>> Begin computation
Python command line: egap/eGap -m 4096 single_chr22_40x_data.fasta 
--- Phase 1 ---
1392.864398
RAM = 4.00 GB
max(chunk) = 858993459 symbols
K = 1
N = 1550100297
CHUNKS = 1
sizeof(int_t) = 4 bytes
total:
CLOCK = 1392.864398 TIME = 1393.000000
malloc_count ### exiting, total: 3,511,772,543,181,029, peak: 7,750,522,093, current: 4,096
--- Phase 2 ---
Command line:
egap/gap2 -A8 -g8 -vaE single_chr22_40x_data.fasta
Single BWT in input and no LCP/dBG computation. I have nothing to do!
Elapsed time: 0.0000 secs
Computing time: 0.0001 secs
Size of merged BWT: 1550100296 Alphabet size: 0
Microseconds per symbol: 0.0000
Peak memory allocation: 8744 bytes, 0.0000 bytes/symbol
>>> End test

**Comment by felipelouza** [comment]
Dear @yanboANU, could you check if the problem is solved with the new commit (git pull, make and run)? I guess it was a simple casting issue. 
Also, could you tell me which OS and compiler version are you using?
Many thanks!

**Comment by yanboANU** [comment]
Sorry, I didnot reply in time.
I git pull,  make and run. Still have that problem(.bwt include a lot of "1“). 
My OS and compiler version are: Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19).

**Comment by yanboANU** [comment]
I found the reason. Thanks.

**Comment by felipelouza** [comment]
Hi @yanboANU, please which was the problem?
Thanks!

**Comment by yanboANU** [comment]
It's my fault. I transfer fastq file to fasta file like this:
cat data.fastq  | awk 'BEGIN{i=0}{ if(i%4==0 || i%4==1){ print $0} i+=1;}' >data.fasta
Then eGap -m 4096 data.fasta, error happen.
If eGap -m 4096 data.fastq, it's correct. And rewrite fasta by python, also correct. 
I should not transfer like that.

**Comment by felipelouza** [comment]
I see! No problem then. Thanks for the clarification.
Cheers!
