### ISSUE TITLE
Paired-End Reads

### ISSUE THREAD

**Issue by elder099** [felipelouza/egap#6]
Does this tool support an input of paired end reads R{1,2}? Is it a planned feature?
If not, does an interleaved fastq file suffice?

Thanks.

**Comment by felipelouza** [comment]
Dear @elder099, there is no special case for FASTQ files with paired-end reads.

Each file is handled as the concatenation of single strings (or reads), interleaved FASTQ files will be handle in the same way. The ordering in the concatenation follows the same in the file. I guess one could interpret odd id's as strings from R1 and even id's from R2. The ids are given if you compute the Document-array.

I hope it can helps you.

All the best!
